#omnirob

  #Publish all joint states---------------------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Forward Position Trajectory Controller ------------------------------
  lrmate200id7l_joint_trajectory_position_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      
    constraints: 
      goal_time: 1.5                   # Override default
      stopped_velocity_tolerance: 0.05 # Override default
      joint_1:
        trajectory: 0.05               # Not enforced if unspecified
        goal: 0.01                     # Not enforced if unspecified
      joint_2:
        trajectory: 0.5              # Not enforced if unspecified
        goal: 0.01                     # Not enforced if unspecified
      joint_3:
        trajectory: 0.05               # Not enforced if unspecified
        goal: 0.01                     # Not enforced if unspecified
      joint_4:
        trajectory: 0.05              # Not enforced if unspecified
        goal: 0.01                     # Not enforced if unspecified
      joint_5:
        trajectory: 0.05              # Not enforced if unspecified
        goal: 0.01                     # Not enforced if unspecified
      joint_6:
        trajectory: 0.05               # Not enforced if unspecified
        goal: 0.01                     # Not enforced if unspecified  
   
